//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public System.Guid AdID { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string Url { get; set; }
        public int Hits { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Sort { get; set; }
        public bool IsShow { get; set; }
        public string Module { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
    }
}
