//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveRecord
    {
        public System.Guid RecordID { get; set; }
        public System.Guid ApproveRelateID { get; set; }
        public string ApproveNode { get; set; }
        public string Comments { get; set; }
        public string ApproveResult { get; set; }
        public System.Guid Approver { get; set; }
        public string ApplyType { get; set; }
        public System.Guid Applicant { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
