//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandPublish
    {
        public System.Guid DemandID { get; set; }
        public string CompanyName { get; set; }
        public string Contacts { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime FoundedTime { get; set; }
        public int Members { get; set; }
        public string ProjectDescription { get; set; }
        public string DemandDescription { get; set; }
        public string IntentionPartner { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string Category { get; set; }
    
        public virtual User User { get; set; }
    }
}
