//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancingRequirements
    {
        public System.Guid FRID { get; set; }
        public string ProductionName { get; set; }
        public string ProjectLogo { get; set; }
        public string CompanyDescription { get; set; }
        public string ProductionDescription { get; set; }
        public string Industry { get; set; }
        public decimal FinancingAmount { get; set; }
        public string Status { get; set; }
        public string DevelopmentalStage { get; set; }
        public string MarketAnalysis { get; set; }
        public string OtherInfo { get; set; }
        public string CoreTeam { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string PermissionControl { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
    }
}
