//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public Functions()
        {
            this.Role_Functions = new HashSet<Role_Functions>();
        }
    
        public System.Guid FunctionID { get; set; }
        public string FunctionName { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Controller { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Sort { get; set; }
    
        public virtual ICollection<Role_Functions> Role_Functions { get; set; }
    }
}
