//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncubatorProjects
    {
        public System.Guid ProjectID { get; set; }
        public System.Guid IncubatorID { get; set; }
        public string ProjectType { get; set; }
        public string ProjectPicture { get; set; }
        public string Description { get; set; }
    
        public virtual IncubatorInformation IncubatorInformation { get; set; }
    }
}
