//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncubatorApply
    {
        public IncubatorApply()
        {
            this.IncubatorApprove = new HashSet<IncubatorApprove>();
        }
    
        public System.Guid ApplyID { get; set; }
        public string ProjectName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTel { get; set; }
        public string ProjectOwner { get; set; }
        public string ContactTel { get; set; }
        public string Email { get; set; }
        public string TeamMembers { get; set; }
        public string ProductDescription { get; set; }
        public string CoreStaffResume { get; set; }
        public string MarketRiskAnalysis { get; set; }
        public string FinancingSituation { get; set; }
        public System.Guid IncubatorID { get; set; }
        public string ApplyStatus { get; set; }
        public Nullable<bool> IsSign { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<IncubatorApprove> IncubatorApprove { get; set; }
    }
}
