//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncubatorInformation
    {
        public IncubatorInformation()
        {
            this.IncubatorApprove = new HashSet<IncubatorApprove>();
            this.IncubatorProjects = new HashSet<IncubatorProjects>();
        }
    
        public System.Guid IncubatorID { get; set; }
        public string IncubatorName { get; set; }
        public string OperationAddress { get; set; }
        public System.DateTime RegTime { get; set; }
        public string Logo { get; set; }
        public bool FinancialSupport { get; set; }
        public string Description { get; set; }
        public string Service { get; set; }
        public string SiteFavorable { get; set; }
        public string OtherService { get; set; }
        public string IndustryRequirement { get; set; }
        public string LocationRequirement { get; set; }
        public string OtherRequirement { get; set; }
        public System.Guid RoleID { get; set; }
        public Nullable<decimal> Sort { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<IncubatorApprove> IncubatorApprove { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<IncubatorProjects> IncubatorProjects { get; set; }
    }
}
