//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorInformation
    {
        public System.Guid UserID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLogo { get; set; }
        public string FundScale { get; set; }
        public string InvestmentField { get; set; }
        public string InvestorName { get; set; }
        public string Email { get; set; }
        public string InvestmentStage { get; set; }
        public string Address { get; set; }
        public string InvestmentCase { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
    }
}
