//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid MessageID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string MsgType { get; set; }
        public Nullable<System.Guid> SessionID { get; set; }
        public System.Guid SendFrom { get; set; }
        public System.Guid SendTo { get; set; }
        public string Status { get; set; }
        public bool DeleteFlagS { get; set; }
        public bool DeleteFlagR { get; set; }
        public bool IsPop { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
