//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeApply
    {
        public OfficeApply()
        {
            this.OfficeApplyWorkExperience = new HashSet<OfficeApplyWorkExperience>();
        }
    
        public System.Guid ApplyID { get; set; }
        public string ProjectOwner { get; set; }
        public string Gender { get; set; }
        public string Degree { get; set; }
        public string Specialty { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Diplomas { get; set; }
        public string IntellectualProperty { get; set; }
        public string CompanyName { get; set; }
        public decimal RegisteredCapital { get; set; }
        public decimal DemandForSpace { get; set; }
        public int InitialStaff { get; set; }
        public string ProductDescription { get; set; }
        public string MemberDescription { get; set; }
        public string FinancingAndRevenue { get; set; }
        public string ApplyStatus { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<OfficeApplyWorkExperience> OfficeApplyWorkExperience { get; set; }
        public virtual User User { get; set; }
    }
}
