//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.IncubatorInformation = new HashSet<IncubatorInformation>();
            this.Role_Functions = new HashSet<Role_Functions>();
            this.User_Roles = new HashSet<User_Roles>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<IncubatorInformation> IncubatorInformation { get; set; }
        public virtual ICollection<Role_Functions> Role_Functions { get; set; }
        public virtual ICollection<User_Roles> User_Roles { get; set; }
    }
}
