//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISPIncubatorOnlinePlatformEntities : DbContext
    {
        public SISPIncubatorOnlinePlatformEntities()
            : base("name=SISPIncubatorOnlinePlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AboutUs> AboutUs { get; set; }
        public DbSet<ActivityImages> ActivityImages { get; set; }
        public DbSet<ActivityPublishApply> ActivityPublishApply { get; set; }
        public DbSet<ActivitySignUp> ActivitySignUp { get; set; }
        public DbSet<Advertisement> Advertisement { get; set; }
        public DbSet<AgreementAttachment> AgreementAttachment { get; set; }
        public DbSet<AgreementTemplate> AgreementTemplate { get; set; }
        public DbSet<ApproveRecord> ApproveRecord { get; set; }
        public DbSet<BlockedIP> BlockedIP { get; set; }
        public DbSet<DemandPublish> DemandPublish { get; set; }
        public DbSet<Dictionary> Dictionary { get; set; }
        public DbSet<FinancingRequirementFollow> FinancingRequirementFollow { get; set; }
        public DbSet<FinancingRequirements> FinancingRequirements { get; set; }
        public DbSet<Function_Actions> Function_Actions { get; set; }
        public DbSet<Functions> Functions { get; set; }
        public DbSet<IncubatorActivityApply> IncubatorActivityApply { get; set; }
        public DbSet<IncubatorApply> IncubatorApply { get; set; }
        public DbSet<IncubatorApprove> IncubatorApprove { get; set; }
        public DbSet<IncubatorInformation> IncubatorInformation { get; set; }
        public DbSet<IncubatorProjects> IncubatorProjects { get; set; }
        public DbSet<InvestorInformation> InvestorInformation { get; set; }
        public DbSet<LinkList> LinkList { get; set; }
        public DbSet<LoginLog> LoginLog { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<OfficeApply> OfficeApply { get; set; }
        public DbSet<OfficeApplyWorkExperience> OfficeApplyWorkExperience { get; set; }
        public DbSet<RequestRecords> RequestRecords { get; set; }
        public DbSet<Role_Functions> Role_Functions { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<ServicePublish> ServicePublish { get; set; }
        public DbSet<SMSValidateCode> SMSValidateCode { get; set; }
        public DbSet<SuccessfulCase> SuccessfulCase { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<User_Roles> User_Roles { get; set; }
        public DbSet<UserExtension> UserExtension { get; set; }
        public DbSet<WeChat> WeChat { get; set; }
        public DbSet<WeChatAccessToken> WeChatAccessToken { get; set; }
        public DbSet<WeChatRandom> WeChatRandom { get; set; }
    }
}
