//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPIncubatorOnlinePlatform.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AboutUs = new HashSet<AboutUs>();
            this.ActivityPublishApply = new HashSet<ActivityPublishApply>();
            this.ActivitySignUp = new HashSet<ActivitySignUp>();
            this.Advertisement = new HashSet<Advertisement>();
            this.ApproveRecord = new HashSet<ApproveRecord>();
            this.ApproveRecord1 = new HashSet<ApproveRecord>();
            this.DemandPublish = new HashSet<DemandPublish>();
            this.FinancingRequirementFollow = new HashSet<FinancingRequirementFollow>();
            this.FinancingRequirements = new HashSet<FinancingRequirements>();
            this.IncubatorActivityApply = new HashSet<IncubatorActivityApply>();
            this.IncubatorApply = new HashSet<IncubatorApply>();
            this.Message = new HashSet<Message>();
            this.Message1 = new HashSet<Message>();
            this.OfficeApply = new HashSet<OfficeApply>();
            this.ServicePublish = new HashSet<ServicePublish>();
            this.SuccessfulCase = new HashSet<SuccessfulCase>();
            this.User_Roles = new HashSet<User_Roles>();
            this.WeChat = new HashSet<WeChat>();
        }
    
        public System.Guid UserID { get; set; }
        public string Mobile { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool Status { get; set; }
        public string LoginIP { get; set; }
        public Nullable<bool> Flag { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<AboutUs> AboutUs { get; set; }
        public virtual ICollection<ActivityPublishApply> ActivityPublishApply { get; set; }
        public virtual ICollection<ActivitySignUp> ActivitySignUp { get; set; }
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual ICollection<ApproveRecord> ApproveRecord { get; set; }
        public virtual ICollection<ApproveRecord> ApproveRecord1 { get; set; }
        public virtual ICollection<DemandPublish> DemandPublish { get; set; }
        public virtual ICollection<FinancingRequirementFollow> FinancingRequirementFollow { get; set; }
        public virtual ICollection<FinancingRequirements> FinancingRequirements { get; set; }
        public virtual ICollection<IncubatorActivityApply> IncubatorActivityApply { get; set; }
        public virtual ICollection<IncubatorApply> IncubatorApply { get; set; }
        public virtual InvestorInformation InvestorInformation { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual ICollection<OfficeApply> OfficeApply { get; set; }
        public virtual ICollection<ServicePublish> ServicePublish { get; set; }
        public virtual ICollection<SuccessfulCase> SuccessfulCase { get; set; }
        public virtual ICollection<User_Roles> User_Roles { get; set; }
        public virtual ICollection<WeChat> WeChat { get; set; }
    }
}
